### ISSUE TITLE
can rx-directory output be "throttled"?

### ISSUE THREAD

**Issue by darrencruse** [JosephMoniz/rx-directory#1]
Hi Joseph this is really just a question.

I'm brand new to RxJs but stumbled on your rx-directory module today and was using it for a little program where I needed to run over the files under a certain directory tree and identify any that are missing from our amazon s3 account.

The only thing that makes it a little painful is we have 1.4TB of files in our S3 account!

When I started using rx-directory this morning I guess I was kind of naive I thought Rx would somehow lazily be walking through the directory tree as I processed each filename downstream.

But from my testing and a little reading I think I see that's not really the way RxJs works?

Do you know otherwise?  Or do you know any way that I could limit the number of filenames that flow downstream in my RxJs pipeline?

What I'm trying to do is reduce both the amount of memory needed to hold all the filenames in memory, as well as limit the number of concurrent network requests I'm making to amazon S3 at any one time (so the operations people at work don't kill me for bringing our network to it's knees?).

Thanks and sorry to bother you (I'm new to this and really still trying to understand RxJs).

**Comment by JosephMoniz** [comment]
Hey @darrencruse 

Sorry for the late response. What you described is a very common problem in just about any fully asynchronous system known as `back pressure`.

There are some pretty good and diverse answers to dealing with back pressure in reactive systems.

Heres a good resource to get you started: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md

FYI: I think controlled observables may be what you're looking for.
